# Generated by Django 2.1.4 on 2019-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_animal_uploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='animal',
            name='uploaded_image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
