# Generated by Django 2.1.4 on 2019-05-11 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20190510_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Date'),
        ),
    ]
