# Generated by Django 2.1.4 on 2019-05-11 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Дата на обявата '),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Качи снимка на животното '),
        ),
    ]
