# Generated by Django 2.1.4 on 2019-05-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_auto_20190511_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundOrLost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_or_lost', models.CharField(max_length=50)),
            ],
        ),
    ]
