# Generated by Django 2.1.4 on 2019-05-11 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_foundorlost'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='found_or_lost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='animals.FoundOrLost'),
        ),
    ]
