# Generated by Django 2.1.4 on 2019-05-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_auto_20190511_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='Статус на животното',
            new_name='found_or_lost',
        ),
    ]
