# Generated by Django 2.1.4 on 2019-05-12 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0010_auto_20190511_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='animal',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
